version: "2.4"
services:
  pingaccess:
    image: pingidentity/pingaccess:edge
    command: wait-for pingfederate:9031 -t 420 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingaccess
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet-dmz
    volumes:
      - pingaccess-out:/opt/out

  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      #- SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      #- SERVER_PROFILE_PATH=baseline/pingfederate
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal
    volumes:
      - pingfederate-out:/opt/out
      - ./serverProfiles/pingFederate/:/opt/in

  # User Passwords are here: https://github.com/pingidentity/pingidentity-server-profiles/blob/master/baseline/pingdirectory/pd.profile/ldif/userRoot/10-users.ldif
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      #- SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      #- SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
      - PING_IDENTITY_ACCEPT_EULA=YES
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet-internal
    volumes:
      - pingdirectory-out:/opt/out
      - ./serverProfiles/pingDirectory/:/opt/in

  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks:
      - pingnet-internal

networks:
    pingnet-internal:
    pingnet-dmz:

volumes:
  pingaccess-out:
  pingfederate-out:
  pingdirectory-out:
